import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron, Inter  } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import PreLoader from "./sections/preLoader";
import LenisProvider from "./providers/lenisProvider";

const orbitron = Orbitron({
    variable: "--font-title",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
    display: "swap"
});

const inter = Inter({
    variable: "--font-body",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    display: "swap"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const colors = {
    primary: "#190223",
    secondary: "#904191"
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const headerlist = await headers();

    const ua = headerlist.get("user-agent") || "";
    const isMobile = /Android|iPhone|iPad|iPod/i.test(ua);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${inter.variable} antialiased`}
      >


          {!isMobile && <PreLoader />}
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
